export const FETCH_QUIZES_START='FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS='FETCH_QUIZES_SUCCESS'
<<<<<<< HEAD
export const FETCH_QUIZES_ERROR='FETCH_QUIZES_ERROR'
export const FETCH_QUIZ_SUCCESS='FETCH_QUIZ_SUCCESS'
export const QUIZ_SET_STATE= 'QUIZ_SET_STATE'
export const FINISH_QUIZ='FINISH_QUIZ'
export const QUIZ_NEXT_QUIESTION='QUIZ_NEXT_QUIESTION'
export const QUIZ_RETRY='QUIZ_RETRY'
=======
export const FETCH_QUIZES_ERROR='FETCH_QUIZES_ERROR'
>>>>>>> 2292d18632268ed4477212b68556a710b0676df1
